# spring.application.name=JPA


# #mysql database configurations
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url = jdbc:mysql://localhost:3306/jpa
# spring.datasource.username = root
# spring.datasource.password = 12345678
# spring.jpa.show-sql=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
     
